/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheindustrialmetaverseRouteImport } from './routes/theindustrialmetaverse'
import { Route as ReInventingTurnaroundsInTheMetaverseRouteImport } from './routes/re-inventing-turnarounds-in-the-metaverse'
import { Route as DigitalTwinFaqRouteImport } from './routes/digital-twin-faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as AiInPharmaceuticalManufacturingRouteImport } from './routes/ai-in-pharmaceutical-manufacturing'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolutionsVirtualRealityAndAugmentedRealityRouteImport } from './routes/solutions.virtual-reality-and-augmented-reality'
import { Route as SolutionsRemotePerformanceMonitoringRouteImport } from './routes/solutions.remote-performance-monitoring'
import { Route as SolutionsRealTimeOptimizationRouteImport } from './routes/solutions.real-time-optimization'
import { Route as SolutionsProcessPerformancePredictionRouteImport } from './routes/solutions.process-performance-prediction'
import { Route as SolutionsDecarbonizationRouteImport } from './routes/solutions.decarbonization'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PlatformViziCopilotGenAiRouteImport } from './routes/platform.vizi-copilot-gen-ai'
import { Route as PlatformViziCopilotRouteImport } from './routes/platform.vizi-copilot'
import { Route as PlatformVSmartDocxRouteImport } from './routes/platform.v-smart-docx'
import { Route as PlatformVPlantRouteImport } from './routes/platform.v-plant'
import { Route as PlatformSignalMinerRouteImport } from './routes/platform.signal-miner'
import { Route as PlatformMicrosoftFabricExpertiseRouteImport } from './routes/platform.microsoft-fabric-expertise'
import { Route as InsightsInsightsDigitalTwinResourceCenterRouteImport } from './routes/insights.insights-digital-twin-resource-center'
import { Route as IndustriesDigitalTwinForPowerAndEnergyRouteImport } from './routes/industries.digital-twin-for-power-and-energy'
import { Route as IndustriesDigitalTwinForOilAndGasRouteImport } from './routes/industries.digital-twin-for-oil-and-gas'
import { Route as IndustriesDigitalTwinForManufacturingRouteImport } from './routes/industries.digital-twin-for-manufacturing'
import { Route as IndustriesDigitalTwinForCementRouteImport } from './routes/industries.digital-twin-for-cement'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TheindustrialmetaverseRoute = TheindustrialmetaverseRouteImport.update({
  id: '/theindustrialmetaverse',
  path: '/theindustrialmetaverse',
  getParentRoute: () => rootRouteImport,
} as any)
const ReInventingTurnaroundsInTheMetaverseRoute =
  ReInventingTurnaroundsInTheMetaverseRouteImport.update({
    id: '/re-inventing-turnarounds-in-the-metaverse',
    path: '/re-inventing-turnarounds-in-the-metaverse',
    getParentRoute: () => rootRouteImport,
  } as any)
const DigitalTwinFaqRoute = DigitalTwinFaqRouteImport.update({
  id: '/digital-twin-faq',
  path: '/digital-twin-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInPharmaceuticalManufacturingRoute =
  AiInPharmaceuticalManufacturingRouteImport.update({
    id: '/ai-in-pharmaceutical-manufacturing',
    path: '/ai-in-pharmaceutical-manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsVirtualRealityAndAugmentedRealityRoute =
  SolutionsVirtualRealityAndAugmentedRealityRouteImport.update({
    id: '/solutions/virtual-reality-and-augmented-reality',
    path: '/solutions/virtual-reality-and-augmented-reality',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsRemotePerformanceMonitoringRoute =
  SolutionsRemotePerformanceMonitoringRouteImport.update({
    id: '/solutions/remote-performance-monitoring',
    path: '/solutions/remote-performance-monitoring',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsRealTimeOptimizationRoute =
  SolutionsRealTimeOptimizationRouteImport.update({
    id: '/solutions/real-time-optimization',
    path: '/solutions/real-time-optimization',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsProcessPerformancePredictionRoute =
  SolutionsProcessPerformancePredictionRouteImport.update({
    id: '/solutions/process-performance-prediction',
    path: '/solutions/process-performance-prediction',
    getParentRoute: () => rootRouteImport,
  } as any)
const SolutionsDecarbonizationRoute =
  SolutionsDecarbonizationRouteImport.update({
    id: '/solutions/decarbonization',
    path: '/solutions/decarbonization',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformViziCopilotGenAiRoute =
  PlatformViziCopilotGenAiRouteImport.update({
    id: '/platform/vizi-copilot-gen-ai',
    path: '/platform/vizi-copilot-gen-ai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformViziCopilotRoute = PlatformViziCopilotRouteImport.update({
  id: '/platform/vizi-copilot',
  path: '/platform/vizi-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformVSmartDocxRoute = PlatformVSmartDocxRouteImport.update({
  id: '/platform/v-smart-docx',
  path: '/platform/v-smart-docx',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformVPlantRoute = PlatformVPlantRouteImport.update({
  id: '/platform/v-plant',
  path: '/platform/v-plant',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSignalMinerRoute = PlatformSignalMinerRouteImport.update({
  id: '/platform/signal-miner',
  path: '/platform/signal-miner',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMicrosoftFabricExpertiseRoute =
  PlatformMicrosoftFabricExpertiseRouteImport.update({
    id: '/platform/microsoft-fabric-expertise',
    path: '/platform/microsoft-fabric-expertise',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsInsightsDigitalTwinResourceCenterRoute =
  InsightsInsightsDigitalTwinResourceCenterRouteImport.update({
    id: '/insights/insights-digital-twin-resource-center',
    path: '/insights/insights-digital-twin-resource-center',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDigitalTwinForPowerAndEnergyRoute =
  IndustriesDigitalTwinForPowerAndEnergyRouteImport.update({
    id: '/industries/digital-twin-for-power-and-energy',
    path: '/industries/digital-twin-for-power-and-energy',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDigitalTwinForOilAndGasRoute =
  IndustriesDigitalTwinForOilAndGasRouteImport.update({
    id: '/industries/digital-twin-for-oil-and-gas',
    path: '/industries/digital-twin-for-oil-and-gas',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDigitalTwinForManufacturingRoute =
  IndustriesDigitalTwinForManufacturingRouteImport.update({
    id: '/industries/digital-twin-for-manufacturing',
    path: '/industries/digital-twin-for-manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDigitalTwinForCementRoute =
  IndustriesDigitalTwinForCementRouteImport.update({
    id: '/industries/digital-twin-for-cement',
    path: '/industries/digital-twin-for-cement',
    getParentRoute: () => rootRouteImport,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/ai-in-pharmaceutical-manufacturing': typeof AiInPharmaceuticalManufacturingRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/digital-twin-faq': typeof DigitalTwinFaqRoute
  '/re-inventing-turnarounds-in-the-metaverse': typeof ReInventingTurnaroundsInTheMetaverseRoute
  '/theindustrialmetaverse': typeof TheindustrialmetaverseRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/digital-twin-for-cement': typeof IndustriesDigitalTwinForCementRoute
  '/industries/digital-twin-for-manufacturing': typeof IndustriesDigitalTwinForManufacturingRoute
  '/industries/digital-twin-for-oil-and-gas': typeof IndustriesDigitalTwinForOilAndGasRoute
  '/industries/digital-twin-for-power-and-energy': typeof IndustriesDigitalTwinForPowerAndEnergyRoute
  '/insights/insights-digital-twin-resource-center': typeof InsightsInsightsDigitalTwinResourceCenterRoute
  '/platform/microsoft-fabric-expertise': typeof PlatformMicrosoftFabricExpertiseRoute
  '/platform/signal-miner': typeof PlatformSignalMinerRoute
  '/platform/v-plant': typeof PlatformVPlantRoute
  '/platform/v-smart-docx': typeof PlatformVSmartDocxRoute
  '/platform/vizi-copilot': typeof PlatformViziCopilotRoute
  '/platform/vizi-copilot-gen-ai': typeof PlatformViziCopilotGenAiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/decarbonization': typeof SolutionsDecarbonizationRoute
  '/solutions/process-performance-prediction': typeof SolutionsProcessPerformancePredictionRoute
  '/solutions/real-time-optimization': typeof SolutionsRealTimeOptimizationRoute
  '/solutions/remote-performance-monitoring': typeof SolutionsRemotePerformanceMonitoringRoute
  '/solutions/virtual-reality-and-augmented-reality': typeof SolutionsVirtualRealityAndAugmentedRealityRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/ai-in-pharmaceutical-manufacturing': typeof AiInPharmaceuticalManufacturingRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/digital-twin-faq': typeof DigitalTwinFaqRoute
  '/re-inventing-turnarounds-in-the-metaverse': typeof ReInventingTurnaroundsInTheMetaverseRoute
  '/theindustrialmetaverse': typeof TheindustrialmetaverseRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/digital-twin-for-cement': typeof IndustriesDigitalTwinForCementRoute
  '/industries/digital-twin-for-manufacturing': typeof IndustriesDigitalTwinForManufacturingRoute
  '/industries/digital-twin-for-oil-and-gas': typeof IndustriesDigitalTwinForOilAndGasRoute
  '/industries/digital-twin-for-power-and-energy': typeof IndustriesDigitalTwinForPowerAndEnergyRoute
  '/insights/insights-digital-twin-resource-center': typeof InsightsInsightsDigitalTwinResourceCenterRoute
  '/platform/microsoft-fabric-expertise': typeof PlatformMicrosoftFabricExpertiseRoute
  '/platform/signal-miner': typeof PlatformSignalMinerRoute
  '/platform/v-plant': typeof PlatformVPlantRoute
  '/platform/v-smart-docx': typeof PlatformVSmartDocxRoute
  '/platform/vizi-copilot': typeof PlatformViziCopilotRoute
  '/platform/vizi-copilot-gen-ai': typeof PlatformViziCopilotGenAiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/decarbonization': typeof SolutionsDecarbonizationRoute
  '/solutions/process-performance-prediction': typeof SolutionsProcessPerformancePredictionRoute
  '/solutions/real-time-optimization': typeof SolutionsRealTimeOptimizationRoute
  '/solutions/remote-performance-monitoring': typeof SolutionsRemotePerformanceMonitoringRoute
  '/solutions/virtual-reality-and-augmented-reality': typeof SolutionsVirtualRealityAndAugmentedRealityRoute
  '/blog': typeof BlogIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/ai-in-pharmaceutical-manufacturing': typeof AiInPharmaceuticalManufacturingRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/digital-twin-faq': typeof DigitalTwinFaqRoute
  '/re-inventing-turnarounds-in-the-metaverse': typeof ReInventingTurnaroundsInTheMetaverseRoute
  '/theindustrialmetaverse': typeof TheindustrialmetaverseRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/industries/digital-twin-for-cement': typeof IndustriesDigitalTwinForCementRoute
  '/industries/digital-twin-for-manufacturing': typeof IndustriesDigitalTwinForManufacturingRoute
  '/industries/digital-twin-for-oil-and-gas': typeof IndustriesDigitalTwinForOilAndGasRoute
  '/industries/digital-twin-for-power-and-energy': typeof IndustriesDigitalTwinForPowerAndEnergyRoute
  '/insights/insights-digital-twin-resource-center': typeof InsightsInsightsDigitalTwinResourceCenterRoute
  '/platform/microsoft-fabric-expertise': typeof PlatformMicrosoftFabricExpertiseRoute
  '/platform/signal-miner': typeof PlatformSignalMinerRoute
  '/platform/v-plant': typeof PlatformVPlantRoute
  '/platform/v-smart-docx': typeof PlatformVSmartDocxRoute
  '/platform/vizi-copilot': typeof PlatformViziCopilotRoute
  '/platform/vizi-copilot-gen-ai': typeof PlatformViziCopilotGenAiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/decarbonization': typeof SolutionsDecarbonizationRoute
  '/solutions/process-performance-prediction': typeof SolutionsProcessPerformancePredictionRoute
  '/solutions/real-time-optimization': typeof SolutionsRealTimeOptimizationRoute
  '/solutions/remote-performance-monitoring': typeof SolutionsRemotePerformanceMonitoringRoute
  '/solutions/virtual-reality-and-augmented-reality': typeof SolutionsVirtualRealityAndAugmentedRealityRoute
  '/blog/': typeof BlogIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/ai-in-pharmaceutical-manufacturing'
    | '/company'
    | '/contact'
    | '/digital-twin-faq'
    | '/re-inventing-turnarounds-in-the-metaverse'
    | '/theindustrialmetaverse'
    | '/blog/$slug'
    | '/industries/digital-twin-for-cement'
    | '/industries/digital-twin-for-manufacturing'
    | '/industries/digital-twin-for-oil-and-gas'
    | '/industries/digital-twin-for-power-and-energy'
    | '/insights/insights-digital-twin-resource-center'
    | '/platform/microsoft-fabric-expertise'
    | '/platform/signal-miner'
    | '/platform/v-plant'
    | '/platform/v-smart-docx'
    | '/platform/vizi-copilot'
    | '/platform/vizi-copilot-gen-ai'
    | '/services/$slug'
    | '/solutions/decarbonization'
    | '/solutions/process-performance-prediction'
    | '/solutions/real-time-optimization'
    | '/solutions/remote-performance-monitoring'
    | '/solutions/virtual-reality-and-augmented-reality'
    | '/blog/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/ai-in-pharmaceutical-manufacturing'
    | '/company'
    | '/contact'
    | '/digital-twin-faq'
    | '/re-inventing-turnarounds-in-the-metaverse'
    | '/theindustrialmetaverse'
    | '/blog/$slug'
    | '/industries/digital-twin-for-cement'
    | '/industries/digital-twin-for-manufacturing'
    | '/industries/digital-twin-for-oil-and-gas'
    | '/industries/digital-twin-for-power-and-energy'
    | '/insights/insights-digital-twin-resource-center'
    | '/platform/microsoft-fabric-expertise'
    | '/platform/signal-miner'
    | '/platform/v-plant'
    | '/platform/v-smart-docx'
    | '/platform/vizi-copilot'
    | '/platform/vizi-copilot-gen-ai'
    | '/services/$slug'
    | '/solutions/decarbonization'
    | '/solutions/process-performance-prediction'
    | '/solutions/real-time-optimization'
    | '/solutions/remote-performance-monitoring'
    | '/solutions/virtual-reality-and-augmented-reality'
    | '/blog'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about-us'
    | '/ai-in-pharmaceutical-manufacturing'
    | '/company'
    | '/contact'
    | '/digital-twin-faq'
    | '/re-inventing-turnarounds-in-the-metaverse'
    | '/theindustrialmetaverse'
    | '/blog/$slug'
    | '/industries/digital-twin-for-cement'
    | '/industries/digital-twin-for-manufacturing'
    | '/industries/digital-twin-for-oil-and-gas'
    | '/industries/digital-twin-for-power-and-energy'
    | '/insights/insights-digital-twin-resource-center'
    | '/platform/microsoft-fabric-expertise'
    | '/platform/signal-miner'
    | '/platform/v-plant'
    | '/platform/v-smart-docx'
    | '/platform/vizi-copilot'
    | '/platform/vizi-copilot-gen-ai'
    | '/services/$slug'
    | '/solutions/decarbonization'
    | '/solutions/process-performance-prediction'
    | '/solutions/real-time-optimization'
    | '/solutions/remote-performance-monitoring'
    | '/solutions/virtual-reality-and-augmented-reality'
    | '/blog/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutUsRoute: typeof AboutUsRoute
  AiInPharmaceuticalManufacturingRoute: typeof AiInPharmaceuticalManufacturingRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  DigitalTwinFaqRoute: typeof DigitalTwinFaqRoute
  ReInventingTurnaroundsInTheMetaverseRoute: typeof ReInventingTurnaroundsInTheMetaverseRoute
  TheindustrialmetaverseRoute: typeof TheindustrialmetaverseRoute
  BlogSlugRoute: typeof BlogSlugRoute
  IndustriesDigitalTwinForCementRoute: typeof IndustriesDigitalTwinForCementRoute
  IndustriesDigitalTwinForManufacturingRoute: typeof IndustriesDigitalTwinForManufacturingRoute
  IndustriesDigitalTwinForOilAndGasRoute: typeof IndustriesDigitalTwinForOilAndGasRoute
  IndustriesDigitalTwinForPowerAndEnergyRoute: typeof IndustriesDigitalTwinForPowerAndEnergyRoute
  InsightsInsightsDigitalTwinResourceCenterRoute: typeof InsightsInsightsDigitalTwinResourceCenterRoute
  PlatformMicrosoftFabricExpertiseRoute: typeof PlatformMicrosoftFabricExpertiseRoute
  PlatformSignalMinerRoute: typeof PlatformSignalMinerRoute
  PlatformVPlantRoute: typeof PlatformVPlantRoute
  PlatformVSmartDocxRoute: typeof PlatformVSmartDocxRoute
  PlatformViziCopilotRoute: typeof PlatformViziCopilotRoute
  PlatformViziCopilotGenAiRoute: typeof PlatformViziCopilotGenAiRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  SolutionsDecarbonizationRoute: typeof SolutionsDecarbonizationRoute
  SolutionsProcessPerformancePredictionRoute: typeof SolutionsProcessPerformancePredictionRoute
  SolutionsRealTimeOptimizationRoute: typeof SolutionsRealTimeOptimizationRoute
  SolutionsRemotePerformanceMonitoringRoute: typeof SolutionsRemotePerformanceMonitoringRoute
  SolutionsVirtualRealityAndAugmentedRealityRoute: typeof SolutionsVirtualRealityAndAugmentedRealityRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theindustrialmetaverse': {
      id: '/theindustrialmetaverse'
      path: '/theindustrialmetaverse'
      fullPath: '/theindustrialmetaverse'
      preLoaderRoute: typeof TheindustrialmetaverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/re-inventing-turnarounds-in-the-metaverse': {
      id: '/re-inventing-turnarounds-in-the-metaverse'
      path: '/re-inventing-turnarounds-in-the-metaverse'
      fullPath: '/re-inventing-turnarounds-in-the-metaverse'
      preLoaderRoute: typeof ReInventingTurnaroundsInTheMetaverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin-faq': {
      id: '/digital-twin-faq'
      path: '/digital-twin-faq'
      fullPath: '/digital-twin-faq'
      preLoaderRoute: typeof DigitalTwinFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-in-pharmaceutical-manufacturing': {
      id: '/ai-in-pharmaceutical-manufacturing'
      path: '/ai-in-pharmaceutical-manufacturing'
      fullPath: '/ai-in-pharmaceutical-manufacturing'
      preLoaderRoute: typeof AiInPharmaceuticalManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/virtual-reality-and-augmented-reality': {
      id: '/solutions/virtual-reality-and-augmented-reality'
      path: '/solutions/virtual-reality-and-augmented-reality'
      fullPath: '/solutions/virtual-reality-and-augmented-reality'
      preLoaderRoute: typeof SolutionsVirtualRealityAndAugmentedRealityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/remote-performance-monitoring': {
      id: '/solutions/remote-performance-monitoring'
      path: '/solutions/remote-performance-monitoring'
      fullPath: '/solutions/remote-performance-monitoring'
      preLoaderRoute: typeof SolutionsRemotePerformanceMonitoringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/real-time-optimization': {
      id: '/solutions/real-time-optimization'
      path: '/solutions/real-time-optimization'
      fullPath: '/solutions/real-time-optimization'
      preLoaderRoute: typeof SolutionsRealTimeOptimizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/process-performance-prediction': {
      id: '/solutions/process-performance-prediction'
      path: '/solutions/process-performance-prediction'
      fullPath: '/solutions/process-performance-prediction'
      preLoaderRoute: typeof SolutionsProcessPerformancePredictionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/decarbonization': {
      id: '/solutions/decarbonization'
      path: '/solutions/decarbonization'
      fullPath: '/solutions/decarbonization'
      preLoaderRoute: typeof SolutionsDecarbonizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/vizi-copilot-gen-ai': {
      id: '/platform/vizi-copilot-gen-ai'
      path: '/platform/vizi-copilot-gen-ai'
      fullPath: '/platform/vizi-copilot-gen-ai'
      preLoaderRoute: typeof PlatformViziCopilotGenAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/vizi-copilot': {
      id: '/platform/vizi-copilot'
      path: '/platform/vizi-copilot'
      fullPath: '/platform/vizi-copilot'
      preLoaderRoute: typeof PlatformViziCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/v-smart-docx': {
      id: '/platform/v-smart-docx'
      path: '/platform/v-smart-docx'
      fullPath: '/platform/v-smart-docx'
      preLoaderRoute: typeof PlatformVSmartDocxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/v-plant': {
      id: '/platform/v-plant'
      path: '/platform/v-plant'
      fullPath: '/platform/v-plant'
      preLoaderRoute: typeof PlatformVPlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/signal-miner': {
      id: '/platform/signal-miner'
      path: '/platform/signal-miner'
      fullPath: '/platform/signal-miner'
      preLoaderRoute: typeof PlatformSignalMinerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/microsoft-fabric-expertise': {
      id: '/platform/microsoft-fabric-expertise'
      path: '/platform/microsoft-fabric-expertise'
      fullPath: '/platform/microsoft-fabric-expertise'
      preLoaderRoute: typeof PlatformMicrosoftFabricExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/insights-digital-twin-resource-center': {
      id: '/insights/insights-digital-twin-resource-center'
      path: '/insights/insights-digital-twin-resource-center'
      fullPath: '/insights/insights-digital-twin-resource-center'
      preLoaderRoute: typeof InsightsInsightsDigitalTwinResourceCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/digital-twin-for-power-and-energy': {
      id: '/industries/digital-twin-for-power-and-energy'
      path: '/industries/digital-twin-for-power-and-energy'
      fullPath: '/industries/digital-twin-for-power-and-energy'
      preLoaderRoute: typeof IndustriesDigitalTwinForPowerAndEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/digital-twin-for-oil-and-gas': {
      id: '/industries/digital-twin-for-oil-and-gas'
      path: '/industries/digital-twin-for-oil-and-gas'
      fullPath: '/industries/digital-twin-for-oil-and-gas'
      preLoaderRoute: typeof IndustriesDigitalTwinForOilAndGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/digital-twin-for-manufacturing': {
      id: '/industries/digital-twin-for-manufacturing'
      path: '/industries/digital-twin-for-manufacturing'
      fullPath: '/industries/digital-twin-for-manufacturing'
      preLoaderRoute: typeof IndustriesDigitalTwinForManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/digital-twin-for-cement': {
      id: '/industries/digital-twin-for-cement'
      path: '/industries/digital-twin-for-cement'
      fullPath: '/industries/digital-twin-for-cement'
      preLoaderRoute: typeof IndustriesDigitalTwinForCementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutUsRoute: AboutUsRoute,
  AiInPharmaceuticalManufacturingRoute: AiInPharmaceuticalManufacturingRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  DigitalTwinFaqRoute: DigitalTwinFaqRoute,
  ReInventingTurnaroundsInTheMetaverseRoute:
    ReInventingTurnaroundsInTheMetaverseRoute,
  TheindustrialmetaverseRoute: TheindustrialmetaverseRoute,
  BlogSlugRoute: BlogSlugRoute,
  IndustriesDigitalTwinForCementRoute: IndustriesDigitalTwinForCementRoute,
  IndustriesDigitalTwinForManufacturingRoute:
    IndustriesDigitalTwinForManufacturingRoute,
  IndustriesDigitalTwinForOilAndGasRoute:
    IndustriesDigitalTwinForOilAndGasRoute,
  IndustriesDigitalTwinForPowerAndEnergyRoute:
    IndustriesDigitalTwinForPowerAndEnergyRoute,
  InsightsInsightsDigitalTwinResourceCenterRoute:
    InsightsInsightsDigitalTwinResourceCenterRoute,
  PlatformMicrosoftFabricExpertiseRoute: PlatformMicrosoftFabricExpertiseRoute,
  PlatformSignalMinerRoute: PlatformSignalMinerRoute,
  PlatformVPlantRoute: PlatformVPlantRoute,
  PlatformVSmartDocxRoute: PlatformVSmartDocxRoute,
  PlatformViziCopilotRoute: PlatformViziCopilotRoute,
  PlatformViziCopilotGenAiRoute: PlatformViziCopilotGenAiRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  SolutionsDecarbonizationRoute: SolutionsDecarbonizationRoute,
  SolutionsProcessPerformancePredictionRoute:
    SolutionsProcessPerformancePredictionRoute,
  SolutionsRealTimeOptimizationRoute: SolutionsRealTimeOptimizationRoute,
  SolutionsRemotePerformanceMonitoringRoute:
    SolutionsRemotePerformanceMonitoringRoute,
  SolutionsVirtualRealityAndAugmentedRealityRoute:
    SolutionsVirtualRealityAndAugmentedRealityRoute,
  BlogIndexRoute: BlogIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
