/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VrTourRequestRouteImport } from './routes/vr-tour-request'
import { Route as ViziCopilotGenAiDemoLinkRouteImport } from './routes/vizi-copilot-gen-ai-demo-link'
import { Route as UtilitiesControlCenterRouteImport } from './routes/utilities-control-center'
import { Route as TheindustrialmetaverseRouteImport } from './routes/theindustrialmetaverse'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SocialDigitalContactRouteImport } from './routes/social-digital-contact'
import { Route as SocialDigitalRouteImport } from './routes/social-digital'
import { Route as SignalMinerContactRouteImport } from './routes/signal-miner-contact'
import { Route as RequestADemoRouteImport } from './routes/request-a-demo'
import { Route as RenewableEnergyWhitepaperRouteImport } from './routes/renewable-energy-whitepaper'
import { Route as ReInventingTurnaroundsInTheMetaverseRouteImport } from './routes/re-inventing-turnarounds-in-the-metaverse'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PowerIndustryWhitepaperRouteImport } from './routes/power-industry-whitepaper'
import { Route as PowerIndustryCaseStudyRouteImport } from './routes/power-industry-case-study'
import { Route as IntelligentDemandForecastRouteImport } from './routes/intelligent-demand-forecast'
import { Route as DigitalTwinFaqRouteImport } from './routes/digital-twin-faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CompanyRouteImport } from './routes/company'
import { Route as CementIndustryWhitepaperRouteImport } from './routes/cement-industry-whitepaper'
import { Route as BuildABusinessCaseRouteImport } from './routes/build-a-business-case'
import { Route as AiInPharmaceuticalManufacturingRouteImport } from './routes/ai-in-pharmaceutical-manufacturing'
import { Route as AboutUsRouteImport } from './routes/about-us'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolutionsIndexRouteImport } from './routes/solutions/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as SolutionsVirtualRealityAndAugmentedRealityRouteImport } from './routes/solutions.virtual-reality-and-augmented-reality'
import { Route as SolutionsRemotePerformanceMonitoringRouteImport } from './routes/solutions.remote-performance-monitoring'
import { Route as SolutionsRealTimeOptimizationRouteImport } from './routes/solutions.real-time-optimization'
import { Route as SolutionsProcessPerformancePredictionRouteImport } from './routes/solutions.process-performance-prediction'
import { Route as SolutionsPredictiveMaintenanceRouteImport } from './routes/solutions.predictive-maintenance'
import { Route as SolutionsMaintainAndSustainRouteImport } from './routes/solutions.maintain-and-sustain'
import { Route as SolutionsDecarbonizationRouteImport } from './routes/solutions.decarbonization'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as PlatformViziCopilotGenAiRouteImport } from './routes/platform.vizi-copilot-gen-ai'
import { Route as PlatformViziCopilotRouteImport } from './routes/platform.vizi-copilot'
import { Route as PlatformVSmartDocxRouteImport } from './routes/platform.v-smart-docx'
import { Route as PlatformVPlantRouteImport } from './routes/platform.v-plant'
import { Route as PlatformSignalMinerRouteImport } from './routes/platform.signal-miner'
import { Route as PlatformMicrosoftFabricExpertiseRouteImport } from './routes/platform.microsoft-fabric-expertise'
import { Route as InsightsInsightsDigitalTwinResourceCenterRouteImport } from './routes/insights/insights-digital-twin-resource-center'
import { Route as IndustriesSugarBioEthanolIndustryRouteImport } from './routes/industries.sugar-bio-ethanol-industry'
import { Route as IndustriesRenewablesEnergyRouteImport } from './routes/industries.renewables-energy'
import { Route as IndustriesDigitalTwinForPowerAndEnergyRouteImport } from './routes/industries.digital-twin-for-power-and-energy'
import { Route as IndustriesDigitalTwinForOilAndGasRouteImport } from './routes/industries.digital-twin-for-oil-and-gas'
import { Route as IndustriesDigitalTwinForManufacturingRouteImport } from './routes/industries.digital-twin-for-manufacturing'
import { Route as IndustriesDigitalTwinForCementRouteImport } from './routes/industries.digital-twin-for-cement'
import { Route as AdminManageColumnsRouteImport } from './routes/admin.manage-columns'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFieldMappingRouteImport } from './routes/admin.field-mapping'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as IndustriesOilAndGasBuildABusinessCaseRouteImport } from './routes/industries/oil-and-gas/build-a-business-case'

const VrTourRequestRoute = VrTourRequestRouteImport.update({
  id: '/vr-tour-request',
  path: '/vr-tour-request',
  getParentRoute: () => rootRouteImport,
} as any)
const ViziCopilotGenAiDemoLinkRoute =
  ViziCopilotGenAiDemoLinkRouteImport.update({
    id: '/vizi-copilot-gen-ai-demo-link',
    path: '/vizi-copilot-gen-ai-demo-link',
    getParentRoute: () => rootRouteImport,
  } as any)
const UtilitiesControlCenterRoute = UtilitiesControlCenterRouteImport.update({
  id: '/utilities-control-center',
  path: '/utilities-control-center',
  getParentRoute: () => rootRouteImport,
} as any)
const TheindustrialmetaverseRoute = TheindustrialmetaverseRouteImport.update({
  id: '/theindustrialmetaverse',
  path: '/theindustrialmetaverse',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialDigitalContactRoute = SocialDigitalContactRouteImport.update({
  id: '/social-digital-contact',
  path: '/social-digital-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialDigitalRoute = SocialDigitalRouteImport.update({
  id: '/social-digital',
  path: '/social-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const SignalMinerContactRoute = SignalMinerContactRouteImport.update({
  id: '/signal-miner-contact',
  path: '/signal-miner-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestADemoRoute = RequestADemoRouteImport.update({
  id: '/request-a-demo',
  path: '/request-a-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const RenewableEnergyWhitepaperRoute =
  RenewableEnergyWhitepaperRouteImport.update({
    id: '/renewable-energy-whitepaper',
    path: '/renewable-energy-whitepaper',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReInventingTurnaroundsInTheMetaverseRoute =
  ReInventingTurnaroundsInTheMetaverseRouteImport.update({
    id: '/re-inventing-turnarounds-in-the-metaverse',
    path: '/re-inventing-turnarounds-in-the-metaverse',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerIndustryWhitepaperRoute = PowerIndustryWhitepaperRouteImport.update({
  id: '/power-industry-whitepaper',
  path: '/power-industry-whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const PowerIndustryCaseStudyRoute = PowerIndustryCaseStudyRouteImport.update({
  id: '/power-industry-case-study',
  path: '/power-industry-case-study',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligentDemandForecastRoute =
  IntelligentDemandForecastRouteImport.update({
    id: '/intelligent-demand-forecast',
    path: '/intelligent-demand-forecast',
    getParentRoute: () => rootRouteImport,
  } as any)
const DigitalTwinFaqRoute = DigitalTwinFaqRouteImport.update({
  id: '/digital-twin-faq',
  path: '/digital-twin-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CompanyRoute = CompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => rootRouteImport,
} as any)
const CementIndustryWhitepaperRoute =
  CementIndustryWhitepaperRouteImport.update({
    id: '/cement-industry-whitepaper',
    path: '/cement-industry-whitepaper',
    getParentRoute: () => rootRouteImport,
  } as any)
const BuildABusinessCaseRoute = BuildABusinessCaseRouteImport.update({
  id: '/build-a-business-case',
  path: '/build-a-business-case',
  getParentRoute: () => rootRouteImport,
} as any)
const AiInPharmaceuticalManufacturingRoute =
  AiInPharmaceuticalManufacturingRouteImport.update({
    id: '/ai-in-pharmaceutical-manufacturing',
    path: '/ai-in-pharmaceutical-manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const AboutUsRoute = AboutUsRouteImport.update({
  id: '/about-us',
  path: '/about-us',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsIndexRoute = SolutionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SolutionsRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsVirtualRealityAndAugmentedRealityRoute =
  SolutionsVirtualRealityAndAugmentedRealityRouteImport.update({
    id: '/virtual-reality-and-augmented-reality',
    path: '/virtual-reality-and-augmented-reality',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsRemotePerformanceMonitoringRoute =
  SolutionsRemotePerformanceMonitoringRouteImport.update({
    id: '/remote-performance-monitoring',
    path: '/remote-performance-monitoring',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsRealTimeOptimizationRoute =
  SolutionsRealTimeOptimizationRouteImport.update({
    id: '/real-time-optimization',
    path: '/real-time-optimization',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsProcessPerformancePredictionRoute =
  SolutionsProcessPerformancePredictionRouteImport.update({
    id: '/process-performance-prediction',
    path: '/process-performance-prediction',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsPredictiveMaintenanceRoute =
  SolutionsPredictiveMaintenanceRouteImport.update({
    id: '/predictive-maintenance',
    path: '/predictive-maintenance',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsMaintainAndSustainRoute =
  SolutionsMaintainAndSustainRouteImport.update({
    id: '/maintain-and-sustain',
    path: '/maintain-and-sustain',
    getParentRoute: () => SolutionsRoute,
  } as any)
const SolutionsDecarbonizationRoute =
  SolutionsDecarbonizationRouteImport.update({
    id: '/decarbonization',
    path: '/decarbonization',
    getParentRoute: () => SolutionsRoute,
  } as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformViziCopilotGenAiRoute =
  PlatformViziCopilotGenAiRouteImport.update({
    id: '/platform/vizi-copilot-gen-ai',
    path: '/platform/vizi-copilot-gen-ai',
    getParentRoute: () => rootRouteImport,
  } as any)
const PlatformViziCopilotRoute = PlatformViziCopilotRouteImport.update({
  id: '/platform/vizi-copilot',
  path: '/platform/vizi-copilot',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformVSmartDocxRoute = PlatformVSmartDocxRouteImport.update({
  id: '/platform/v-smart-docx',
  path: '/platform/v-smart-docx',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformVPlantRoute = PlatformVPlantRouteImport.update({
  id: '/platform/v-plant',
  path: '/platform/v-plant',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSignalMinerRoute = PlatformSignalMinerRouteImport.update({
  id: '/platform/signal-miner',
  path: '/platform/signal-miner',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformMicrosoftFabricExpertiseRoute =
  PlatformMicrosoftFabricExpertiseRouteImport.update({
    id: '/platform/microsoft-fabric-expertise',
    path: '/platform/microsoft-fabric-expertise',
    getParentRoute: () => rootRouteImport,
  } as any)
const InsightsInsightsDigitalTwinResourceCenterRoute =
  InsightsInsightsDigitalTwinResourceCenterRouteImport.update({
    id: '/insights/insights-digital-twin-resource-center',
    path: '/insights/insights-digital-twin-resource-center',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesSugarBioEthanolIndustryRoute =
  IndustriesSugarBioEthanolIndustryRouteImport.update({
    id: '/industries/sugar-bio-ethanol-industry',
    path: '/industries/sugar-bio-ethanol-industry',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesRenewablesEnergyRoute =
  IndustriesRenewablesEnergyRouteImport.update({
    id: '/industries/renewables-energy',
    path: '/industries/renewables-energy',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDigitalTwinForPowerAndEnergyRoute =
  IndustriesDigitalTwinForPowerAndEnergyRouteImport.update({
    id: '/industries/digital-twin-for-power-and-energy',
    path: '/industries/digital-twin-for-power-and-energy',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDigitalTwinForOilAndGasRoute =
  IndustriesDigitalTwinForOilAndGasRouteImport.update({
    id: '/industries/digital-twin-for-oil-and-gas',
    path: '/industries/digital-twin-for-oil-and-gas',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDigitalTwinForManufacturingRoute =
  IndustriesDigitalTwinForManufacturingRouteImport.update({
    id: '/industries/digital-twin-for-manufacturing',
    path: '/industries/digital-twin-for-manufacturing',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndustriesDigitalTwinForCementRoute =
  IndustriesDigitalTwinForCementRouteImport.update({
    id: '/industries/digital-twin-for-cement',
    path: '/industries/digital-twin-for-cement',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminManageColumnsRoute = AdminManageColumnsRouteImport.update({
  id: '/admin/manage-columns',
  path: '/admin/manage-columns',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFieldMappingRoute = AdminFieldMappingRouteImport.update({
  id: '/admin/field-mapping',
  path: '/admin/field-mapping',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesOilAndGasBuildABusinessCaseRoute =
  IndustriesOilAndGasBuildABusinessCaseRouteImport.update({
    id: '/industries/oil-and-gas/build-a-business-case',
    path: '/industries/oil-and-gas/build-a-business-case',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/ai-in-pharmaceutical-manufacturing': typeof AiInPharmaceuticalManufacturingRoute
  '/build-a-business-case': typeof BuildABusinessCaseRoute
  '/cement-industry-whitepaper': typeof CementIndustryWhitepaperRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/digital-twin-faq': typeof DigitalTwinFaqRoute
  '/intelligent-demand-forecast': typeof IntelligentDemandForecastRoute
  '/power-industry-case-study': typeof PowerIndustryCaseStudyRoute
  '/power-industry-whitepaper': typeof PowerIndustryWhitepaperRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/re-inventing-turnarounds-in-the-metaverse': typeof ReInventingTurnaroundsInTheMetaverseRoute
  '/renewable-energy-whitepaper': typeof RenewableEnergyWhitepaperRoute
  '/request-a-demo': typeof RequestADemoRoute
  '/signal-miner-contact': typeof SignalMinerContactRoute
  '/social-digital': typeof SocialDigitalRoute
  '/social-digital-contact': typeof SocialDigitalContactRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/theindustrialmetaverse': typeof TheindustrialmetaverseRoute
  '/utilities-control-center': typeof UtilitiesControlCenterRoute
  '/vizi-copilot-gen-ai-demo-link': typeof ViziCopilotGenAiDemoLinkRoute
  '/vr-tour-request': typeof VrTourRequestRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/field-mapping': typeof AdminFieldMappingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage-columns': typeof AdminManageColumnsRoute
  '/industries/digital-twin-for-cement': typeof IndustriesDigitalTwinForCementRoute
  '/industries/digital-twin-for-manufacturing': typeof IndustriesDigitalTwinForManufacturingRoute
  '/industries/digital-twin-for-oil-and-gas': typeof IndustriesDigitalTwinForOilAndGasRoute
  '/industries/digital-twin-for-power-and-energy': typeof IndustriesDigitalTwinForPowerAndEnergyRoute
  '/industries/renewables-energy': typeof IndustriesRenewablesEnergyRoute
  '/industries/sugar-bio-ethanol-industry': typeof IndustriesSugarBioEthanolIndustryRoute
  '/insights/insights-digital-twin-resource-center': typeof InsightsInsightsDigitalTwinResourceCenterRoute
  '/platform/microsoft-fabric-expertise': typeof PlatformMicrosoftFabricExpertiseRoute
  '/platform/signal-miner': typeof PlatformSignalMinerRoute
  '/platform/v-plant': typeof PlatformVPlantRoute
  '/platform/v-smart-docx': typeof PlatformVSmartDocxRoute
  '/platform/vizi-copilot': typeof PlatformViziCopilotRoute
  '/platform/vizi-copilot-gen-ai': typeof PlatformViziCopilotGenAiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/decarbonization': typeof SolutionsDecarbonizationRoute
  '/solutions/maintain-and-sustain': typeof SolutionsMaintainAndSustainRoute
  '/solutions/predictive-maintenance': typeof SolutionsPredictiveMaintenanceRoute
  '/solutions/process-performance-prediction': typeof SolutionsProcessPerformancePredictionRoute
  '/solutions/real-time-optimization': typeof SolutionsRealTimeOptimizationRoute
  '/solutions/remote-performance-monitoring': typeof SolutionsRemotePerformanceMonitoringRoute
  '/solutions/virtual-reality-and-augmented-reality': typeof SolutionsVirtualRealityAndAugmentedRealityRoute
  '/blog/': typeof BlogIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/industries/oil-and-gas/build-a-business-case': typeof IndustriesOilAndGasBuildABusinessCaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/ai-in-pharmaceutical-manufacturing': typeof AiInPharmaceuticalManufacturingRoute
  '/build-a-business-case': typeof BuildABusinessCaseRoute
  '/cement-industry-whitepaper': typeof CementIndustryWhitepaperRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/digital-twin-faq': typeof DigitalTwinFaqRoute
  '/intelligent-demand-forecast': typeof IntelligentDemandForecastRoute
  '/power-industry-case-study': typeof PowerIndustryCaseStudyRoute
  '/power-industry-whitepaper': typeof PowerIndustryWhitepaperRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/re-inventing-turnarounds-in-the-metaverse': typeof ReInventingTurnaroundsInTheMetaverseRoute
  '/renewable-energy-whitepaper': typeof RenewableEnergyWhitepaperRoute
  '/request-a-demo': typeof RequestADemoRoute
  '/signal-miner-contact': typeof SignalMinerContactRoute
  '/social-digital': typeof SocialDigitalRoute
  '/social-digital-contact': typeof SocialDigitalContactRoute
  '/theindustrialmetaverse': typeof TheindustrialmetaverseRoute
  '/utilities-control-center': typeof UtilitiesControlCenterRoute
  '/vizi-copilot-gen-ai-demo-link': typeof ViziCopilotGenAiDemoLinkRoute
  '/vr-tour-request': typeof VrTourRequestRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/field-mapping': typeof AdminFieldMappingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage-columns': typeof AdminManageColumnsRoute
  '/industries/digital-twin-for-cement': typeof IndustriesDigitalTwinForCementRoute
  '/industries/digital-twin-for-manufacturing': typeof IndustriesDigitalTwinForManufacturingRoute
  '/industries/digital-twin-for-oil-and-gas': typeof IndustriesDigitalTwinForOilAndGasRoute
  '/industries/digital-twin-for-power-and-energy': typeof IndustriesDigitalTwinForPowerAndEnergyRoute
  '/industries/renewables-energy': typeof IndustriesRenewablesEnergyRoute
  '/industries/sugar-bio-ethanol-industry': typeof IndustriesSugarBioEthanolIndustryRoute
  '/insights/insights-digital-twin-resource-center': typeof InsightsInsightsDigitalTwinResourceCenterRoute
  '/platform/microsoft-fabric-expertise': typeof PlatformMicrosoftFabricExpertiseRoute
  '/platform/signal-miner': typeof PlatformSignalMinerRoute
  '/platform/v-plant': typeof PlatformVPlantRoute
  '/platform/v-smart-docx': typeof PlatformVSmartDocxRoute
  '/platform/vizi-copilot': typeof PlatformViziCopilotRoute
  '/platform/vizi-copilot-gen-ai': typeof PlatformViziCopilotGenAiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/decarbonization': typeof SolutionsDecarbonizationRoute
  '/solutions/maintain-and-sustain': typeof SolutionsMaintainAndSustainRoute
  '/solutions/predictive-maintenance': typeof SolutionsPredictiveMaintenanceRoute
  '/solutions/process-performance-prediction': typeof SolutionsProcessPerformancePredictionRoute
  '/solutions/real-time-optimization': typeof SolutionsRealTimeOptimizationRoute
  '/solutions/remote-performance-monitoring': typeof SolutionsRemotePerformanceMonitoringRoute
  '/solutions/virtual-reality-and-augmented-reality': typeof SolutionsVirtualRealityAndAugmentedRealityRoute
  '/blog': typeof BlogIndexRoute
  '/solutions': typeof SolutionsIndexRoute
  '/industries/oil-and-gas/build-a-business-case': typeof IndustriesOilAndGasBuildABusinessCaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/about-us': typeof AboutUsRoute
  '/ai-in-pharmaceutical-manufacturing': typeof AiInPharmaceuticalManufacturingRoute
  '/build-a-business-case': typeof BuildABusinessCaseRoute
  '/cement-industry-whitepaper': typeof CementIndustryWhitepaperRoute
  '/company': typeof CompanyRoute
  '/contact': typeof ContactRoute
  '/digital-twin-faq': typeof DigitalTwinFaqRoute
  '/intelligent-demand-forecast': typeof IntelligentDemandForecastRoute
  '/power-industry-case-study': typeof PowerIndustryCaseStudyRoute
  '/power-industry-whitepaper': typeof PowerIndustryWhitepaperRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/re-inventing-turnarounds-in-the-metaverse': typeof ReInventingTurnaroundsInTheMetaverseRoute
  '/renewable-energy-whitepaper': typeof RenewableEnergyWhitepaperRoute
  '/request-a-demo': typeof RequestADemoRoute
  '/signal-miner-contact': typeof SignalMinerContactRoute
  '/social-digital': typeof SocialDigitalRoute
  '/social-digital-contact': typeof SocialDigitalContactRoute
  '/solutions': typeof SolutionsRouteWithChildren
  '/theindustrialmetaverse': typeof TheindustrialmetaverseRoute
  '/utilities-control-center': typeof UtilitiesControlCenterRoute
  '/vizi-copilot-gen-ai-demo-link': typeof ViziCopilotGenAiDemoLinkRoute
  '/vr-tour-request': typeof VrTourRequestRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/field-mapping': typeof AdminFieldMappingRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage-columns': typeof AdminManageColumnsRoute
  '/industries/digital-twin-for-cement': typeof IndustriesDigitalTwinForCementRoute
  '/industries/digital-twin-for-manufacturing': typeof IndustriesDigitalTwinForManufacturingRoute
  '/industries/digital-twin-for-oil-and-gas': typeof IndustriesDigitalTwinForOilAndGasRoute
  '/industries/digital-twin-for-power-and-energy': typeof IndustriesDigitalTwinForPowerAndEnergyRoute
  '/industries/renewables-energy': typeof IndustriesRenewablesEnergyRoute
  '/industries/sugar-bio-ethanol-industry': typeof IndustriesSugarBioEthanolIndustryRoute
  '/insights/insights-digital-twin-resource-center': typeof InsightsInsightsDigitalTwinResourceCenterRoute
  '/platform/microsoft-fabric-expertise': typeof PlatformMicrosoftFabricExpertiseRoute
  '/platform/signal-miner': typeof PlatformSignalMinerRoute
  '/platform/v-plant': typeof PlatformVPlantRoute
  '/platform/v-smart-docx': typeof PlatformVSmartDocxRoute
  '/platform/vizi-copilot': typeof PlatformViziCopilotRoute
  '/platform/vizi-copilot-gen-ai': typeof PlatformViziCopilotGenAiRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/solutions/decarbonization': typeof SolutionsDecarbonizationRoute
  '/solutions/maintain-and-sustain': typeof SolutionsMaintainAndSustainRoute
  '/solutions/predictive-maintenance': typeof SolutionsPredictiveMaintenanceRoute
  '/solutions/process-performance-prediction': typeof SolutionsProcessPerformancePredictionRoute
  '/solutions/real-time-optimization': typeof SolutionsRealTimeOptimizationRoute
  '/solutions/remote-performance-monitoring': typeof SolutionsRemotePerformanceMonitoringRoute
  '/solutions/virtual-reality-and-augmented-reality': typeof SolutionsVirtualRealityAndAugmentedRealityRoute
  '/blog/': typeof BlogIndexRoute
  '/solutions/': typeof SolutionsIndexRoute
  '/industries/oil-and-gas/build-a-business-case': typeof IndustriesOilAndGasBuildABusinessCaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/ai-in-pharmaceutical-manufacturing'
    | '/build-a-business-case'
    | '/cement-industry-whitepaper'
    | '/company'
    | '/contact'
    | '/digital-twin-faq'
    | '/intelligent-demand-forecast'
    | '/power-industry-case-study'
    | '/power-industry-whitepaper'
    | '/privacy-policy'
    | '/re-inventing-turnarounds-in-the-metaverse'
    | '/renewable-energy-whitepaper'
    | '/request-a-demo'
    | '/signal-miner-contact'
    | '/social-digital'
    | '/social-digital-contact'
    | '/solutions'
    | '/theindustrialmetaverse'
    | '/utilities-control-center'
    | '/vizi-copilot-gen-ai-demo-link'
    | '/vr-tour-request'
    | '/admin/analytics'
    | '/admin/enquiries'
    | '/admin/field-mapping'
    | '/admin/login'
    | '/admin/manage-columns'
    | '/industries/digital-twin-for-cement'
    | '/industries/digital-twin-for-manufacturing'
    | '/industries/digital-twin-for-oil-and-gas'
    | '/industries/digital-twin-for-power-and-energy'
    | '/industries/renewables-energy'
    | '/industries/sugar-bio-ethanol-industry'
    | '/insights/insights-digital-twin-resource-center'
    | '/platform/microsoft-fabric-expertise'
    | '/platform/signal-miner'
    | '/platform/v-plant'
    | '/platform/v-smart-docx'
    | '/platform/vizi-copilot'
    | '/platform/vizi-copilot-gen-ai'
    | '/services/$slug'
    | '/solutions/decarbonization'
    | '/solutions/maintain-and-sustain'
    | '/solutions/predictive-maintenance'
    | '/solutions/process-performance-prediction'
    | '/solutions/real-time-optimization'
    | '/solutions/remote-performance-monitoring'
    | '/solutions/virtual-reality-and-augmented-reality'
    | '/blog/'
    | '/solutions/'
    | '/industries/oil-and-gas/build-a-business-case'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/about-us'
    | '/ai-in-pharmaceutical-manufacturing'
    | '/build-a-business-case'
    | '/cement-industry-whitepaper'
    | '/company'
    | '/contact'
    | '/digital-twin-faq'
    | '/intelligent-demand-forecast'
    | '/power-industry-case-study'
    | '/power-industry-whitepaper'
    | '/privacy-policy'
    | '/re-inventing-turnarounds-in-the-metaverse'
    | '/renewable-energy-whitepaper'
    | '/request-a-demo'
    | '/signal-miner-contact'
    | '/social-digital'
    | '/social-digital-contact'
    | '/theindustrialmetaverse'
    | '/utilities-control-center'
    | '/vizi-copilot-gen-ai-demo-link'
    | '/vr-tour-request'
    | '/admin/analytics'
    | '/admin/enquiries'
    | '/admin/field-mapping'
    | '/admin/login'
    | '/admin/manage-columns'
    | '/industries/digital-twin-for-cement'
    | '/industries/digital-twin-for-manufacturing'
    | '/industries/digital-twin-for-oil-and-gas'
    | '/industries/digital-twin-for-power-and-energy'
    | '/industries/renewables-energy'
    | '/industries/sugar-bio-ethanol-industry'
    | '/insights/insights-digital-twin-resource-center'
    | '/platform/microsoft-fabric-expertise'
    | '/platform/signal-miner'
    | '/platform/v-plant'
    | '/platform/v-smart-docx'
    | '/platform/vizi-copilot'
    | '/platform/vizi-copilot-gen-ai'
    | '/services/$slug'
    | '/solutions/decarbonization'
    | '/solutions/maintain-and-sustain'
    | '/solutions/predictive-maintenance'
    | '/solutions/process-performance-prediction'
    | '/solutions/real-time-optimization'
    | '/solutions/remote-performance-monitoring'
    | '/solutions/virtual-reality-and-augmented-reality'
    | '/blog'
    | '/solutions'
    | '/industries/oil-and-gas/build-a-business-case'
  id:
    | '__root__'
    | '/'
    | '/$slug'
    | '/about-us'
    | '/ai-in-pharmaceutical-manufacturing'
    | '/build-a-business-case'
    | '/cement-industry-whitepaper'
    | '/company'
    | '/contact'
    | '/digital-twin-faq'
    | '/intelligent-demand-forecast'
    | '/power-industry-case-study'
    | '/power-industry-whitepaper'
    | '/privacy-policy'
    | '/re-inventing-turnarounds-in-the-metaverse'
    | '/renewable-energy-whitepaper'
    | '/request-a-demo'
    | '/signal-miner-contact'
    | '/social-digital'
    | '/social-digital-contact'
    | '/solutions'
    | '/theindustrialmetaverse'
    | '/utilities-control-center'
    | '/vizi-copilot-gen-ai-demo-link'
    | '/vr-tour-request'
    | '/admin/analytics'
    | '/admin/enquiries'
    | '/admin/field-mapping'
    | '/admin/login'
    | '/admin/manage-columns'
    | '/industries/digital-twin-for-cement'
    | '/industries/digital-twin-for-manufacturing'
    | '/industries/digital-twin-for-oil-and-gas'
    | '/industries/digital-twin-for-power-and-energy'
    | '/industries/renewables-energy'
    | '/industries/sugar-bio-ethanol-industry'
    | '/insights/insights-digital-twin-resource-center'
    | '/platform/microsoft-fabric-expertise'
    | '/platform/signal-miner'
    | '/platform/v-plant'
    | '/platform/v-smart-docx'
    | '/platform/vizi-copilot'
    | '/platform/vizi-copilot-gen-ai'
    | '/services/$slug'
    | '/solutions/decarbonization'
    | '/solutions/maintain-and-sustain'
    | '/solutions/predictive-maintenance'
    | '/solutions/process-performance-prediction'
    | '/solutions/real-time-optimization'
    | '/solutions/remote-performance-monitoring'
    | '/solutions/virtual-reality-and-augmented-reality'
    | '/blog/'
    | '/solutions/'
    | '/industries/oil-and-gas/build-a-business-case'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SlugRoute: typeof SlugRoute
  AboutUsRoute: typeof AboutUsRoute
  AiInPharmaceuticalManufacturingRoute: typeof AiInPharmaceuticalManufacturingRoute
  BuildABusinessCaseRoute: typeof BuildABusinessCaseRoute
  CementIndustryWhitepaperRoute: typeof CementIndustryWhitepaperRoute
  CompanyRoute: typeof CompanyRoute
  ContactRoute: typeof ContactRoute
  DigitalTwinFaqRoute: typeof DigitalTwinFaqRoute
  IntelligentDemandForecastRoute: typeof IntelligentDemandForecastRoute
  PowerIndustryCaseStudyRoute: typeof PowerIndustryCaseStudyRoute
  PowerIndustryWhitepaperRoute: typeof PowerIndustryWhitepaperRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ReInventingTurnaroundsInTheMetaverseRoute: typeof ReInventingTurnaroundsInTheMetaverseRoute
  RenewableEnergyWhitepaperRoute: typeof RenewableEnergyWhitepaperRoute
  RequestADemoRoute: typeof RequestADemoRoute
  SignalMinerContactRoute: typeof SignalMinerContactRoute
  SocialDigitalRoute: typeof SocialDigitalRoute
  SocialDigitalContactRoute: typeof SocialDigitalContactRoute
  SolutionsRoute: typeof SolutionsRouteWithChildren
  TheindustrialmetaverseRoute: typeof TheindustrialmetaverseRoute
  UtilitiesControlCenterRoute: typeof UtilitiesControlCenterRoute
  ViziCopilotGenAiDemoLinkRoute: typeof ViziCopilotGenAiDemoLinkRoute
  VrTourRequestRoute: typeof VrTourRequestRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminFieldMappingRoute: typeof AdminFieldMappingRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminManageColumnsRoute: typeof AdminManageColumnsRoute
  IndustriesDigitalTwinForCementRoute: typeof IndustriesDigitalTwinForCementRoute
  IndustriesDigitalTwinForManufacturingRoute: typeof IndustriesDigitalTwinForManufacturingRoute
  IndustriesDigitalTwinForOilAndGasRoute: typeof IndustriesDigitalTwinForOilAndGasRoute
  IndustriesDigitalTwinForPowerAndEnergyRoute: typeof IndustriesDigitalTwinForPowerAndEnergyRoute
  IndustriesRenewablesEnergyRoute: typeof IndustriesRenewablesEnergyRoute
  IndustriesSugarBioEthanolIndustryRoute: typeof IndustriesSugarBioEthanolIndustryRoute
  InsightsInsightsDigitalTwinResourceCenterRoute: typeof InsightsInsightsDigitalTwinResourceCenterRoute
  PlatformMicrosoftFabricExpertiseRoute: typeof PlatformMicrosoftFabricExpertiseRoute
  PlatformSignalMinerRoute: typeof PlatformSignalMinerRoute
  PlatformVPlantRoute: typeof PlatformVPlantRoute
  PlatformVSmartDocxRoute: typeof PlatformVSmartDocxRoute
  PlatformViziCopilotRoute: typeof PlatformViziCopilotRoute
  PlatformViziCopilotGenAiRoute: typeof PlatformViziCopilotGenAiRoute
  ServicesSlugRoute: typeof ServicesSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
  IndustriesOilAndGasBuildABusinessCaseRoute: typeof IndustriesOilAndGasBuildABusinessCaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vr-tour-request': {
      id: '/vr-tour-request'
      path: '/vr-tour-request'
      fullPath: '/vr-tour-request'
      preLoaderRoute: typeof VrTourRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vizi-copilot-gen-ai-demo-link': {
      id: '/vizi-copilot-gen-ai-demo-link'
      path: '/vizi-copilot-gen-ai-demo-link'
      fullPath: '/vizi-copilot-gen-ai-demo-link'
      preLoaderRoute: typeof ViziCopilotGenAiDemoLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/utilities-control-center': {
      id: '/utilities-control-center'
      path: '/utilities-control-center'
      fullPath: '/utilities-control-center'
      preLoaderRoute: typeof UtilitiesControlCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theindustrialmetaverse': {
      id: '/theindustrialmetaverse'
      path: '/theindustrialmetaverse'
      fullPath: '/theindustrialmetaverse'
      preLoaderRoute: typeof TheindustrialmetaverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-digital-contact': {
      id: '/social-digital-contact'
      path: '/social-digital-contact'
      fullPath: '/social-digital-contact'
      preLoaderRoute: typeof SocialDigitalContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-digital': {
      id: '/social-digital'
      path: '/social-digital'
      fullPath: '/social-digital'
      preLoaderRoute: typeof SocialDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signal-miner-contact': {
      id: '/signal-miner-contact'
      path: '/signal-miner-contact'
      fullPath: '/signal-miner-contact'
      preLoaderRoute: typeof SignalMinerContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-demo': {
      id: '/request-a-demo'
      path: '/request-a-demo'
      fullPath: '/request-a-demo'
      preLoaderRoute: typeof RequestADemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/renewable-energy-whitepaper': {
      id: '/renewable-energy-whitepaper'
      path: '/renewable-energy-whitepaper'
      fullPath: '/renewable-energy-whitepaper'
      preLoaderRoute: typeof RenewableEnergyWhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/re-inventing-turnarounds-in-the-metaverse': {
      id: '/re-inventing-turnarounds-in-the-metaverse'
      path: '/re-inventing-turnarounds-in-the-metaverse'
      fullPath: '/re-inventing-turnarounds-in-the-metaverse'
      preLoaderRoute: typeof ReInventingTurnaroundsInTheMetaverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-industry-whitepaper': {
      id: '/power-industry-whitepaper'
      path: '/power-industry-whitepaper'
      fullPath: '/power-industry-whitepaper'
      preLoaderRoute: typeof PowerIndustryWhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/power-industry-case-study': {
      id: '/power-industry-case-study'
      path: '/power-industry-case-study'
      fullPath: '/power-industry-case-study'
      preLoaderRoute: typeof PowerIndustryCaseStudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligent-demand-forecast': {
      id: '/intelligent-demand-forecast'
      path: '/intelligent-demand-forecast'
      fullPath: '/intelligent-demand-forecast'
      preLoaderRoute: typeof IntelligentDemandForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/digital-twin-faq': {
      id: '/digital-twin-faq'
      path: '/digital-twin-faq'
      fullPath: '/digital-twin-faq'
      preLoaderRoute: typeof DigitalTwinFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/company': {
      id: '/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof CompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cement-industry-whitepaper': {
      id: '/cement-industry-whitepaper'
      path: '/cement-industry-whitepaper'
      fullPath: '/cement-industry-whitepaper'
      preLoaderRoute: typeof CementIndustryWhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-a-business-case': {
      id: '/build-a-business-case'
      path: '/build-a-business-case'
      fullPath: '/build-a-business-case'
      preLoaderRoute: typeof BuildABusinessCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-in-pharmaceutical-manufacturing': {
      id: '/ai-in-pharmaceutical-manufacturing'
      path: '/ai-in-pharmaceutical-manufacturing'
      fullPath: '/ai-in-pharmaceutical-manufacturing'
      preLoaderRoute: typeof AiInPharmaceuticalManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-us': {
      id: '/about-us'
      path: '/about-us'
      fullPath: '/about-us'
      preLoaderRoute: typeof AboutUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/': {
      id: '/solutions/'
      path: '/'
      fullPath: '/solutions/'
      preLoaderRoute: typeof SolutionsIndexRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions/virtual-reality-and-augmented-reality': {
      id: '/solutions/virtual-reality-and-augmented-reality'
      path: '/virtual-reality-and-augmented-reality'
      fullPath: '/solutions/virtual-reality-and-augmented-reality'
      preLoaderRoute: typeof SolutionsVirtualRealityAndAugmentedRealityRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/remote-performance-monitoring': {
      id: '/solutions/remote-performance-monitoring'
      path: '/remote-performance-monitoring'
      fullPath: '/solutions/remote-performance-monitoring'
      preLoaderRoute: typeof SolutionsRemotePerformanceMonitoringRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/real-time-optimization': {
      id: '/solutions/real-time-optimization'
      path: '/real-time-optimization'
      fullPath: '/solutions/real-time-optimization'
      preLoaderRoute: typeof SolutionsRealTimeOptimizationRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/process-performance-prediction': {
      id: '/solutions/process-performance-prediction'
      path: '/process-performance-prediction'
      fullPath: '/solutions/process-performance-prediction'
      preLoaderRoute: typeof SolutionsProcessPerformancePredictionRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/predictive-maintenance': {
      id: '/solutions/predictive-maintenance'
      path: '/predictive-maintenance'
      fullPath: '/solutions/predictive-maintenance'
      preLoaderRoute: typeof SolutionsPredictiveMaintenanceRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/maintain-and-sustain': {
      id: '/solutions/maintain-and-sustain'
      path: '/maintain-and-sustain'
      fullPath: '/solutions/maintain-and-sustain'
      preLoaderRoute: typeof SolutionsMaintainAndSustainRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/solutions/decarbonization': {
      id: '/solutions/decarbonization'
      path: '/decarbonization'
      fullPath: '/solutions/decarbonization'
      preLoaderRoute: typeof SolutionsDecarbonizationRouteImport
      parentRoute: typeof SolutionsRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/vizi-copilot-gen-ai': {
      id: '/platform/vizi-copilot-gen-ai'
      path: '/platform/vizi-copilot-gen-ai'
      fullPath: '/platform/vizi-copilot-gen-ai'
      preLoaderRoute: typeof PlatformViziCopilotGenAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/vizi-copilot': {
      id: '/platform/vizi-copilot'
      path: '/platform/vizi-copilot'
      fullPath: '/platform/vizi-copilot'
      preLoaderRoute: typeof PlatformViziCopilotRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/v-smart-docx': {
      id: '/platform/v-smart-docx'
      path: '/platform/v-smart-docx'
      fullPath: '/platform/v-smart-docx'
      preLoaderRoute: typeof PlatformVSmartDocxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/v-plant': {
      id: '/platform/v-plant'
      path: '/platform/v-plant'
      fullPath: '/platform/v-plant'
      preLoaderRoute: typeof PlatformVPlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/signal-miner': {
      id: '/platform/signal-miner'
      path: '/platform/signal-miner'
      fullPath: '/platform/signal-miner'
      preLoaderRoute: typeof PlatformSignalMinerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/microsoft-fabric-expertise': {
      id: '/platform/microsoft-fabric-expertise'
      path: '/platform/microsoft-fabric-expertise'
      fullPath: '/platform/microsoft-fabric-expertise'
      preLoaderRoute: typeof PlatformMicrosoftFabricExpertiseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights/insights-digital-twin-resource-center': {
      id: '/insights/insights-digital-twin-resource-center'
      path: '/insights/insights-digital-twin-resource-center'
      fullPath: '/insights/insights-digital-twin-resource-center'
      preLoaderRoute: typeof InsightsInsightsDigitalTwinResourceCenterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/sugar-bio-ethanol-industry': {
      id: '/industries/sugar-bio-ethanol-industry'
      path: '/industries/sugar-bio-ethanol-industry'
      fullPath: '/industries/sugar-bio-ethanol-industry'
      preLoaderRoute: typeof IndustriesSugarBioEthanolIndustryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/renewables-energy': {
      id: '/industries/renewables-energy'
      path: '/industries/renewables-energy'
      fullPath: '/industries/renewables-energy'
      preLoaderRoute: typeof IndustriesRenewablesEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/digital-twin-for-power-and-energy': {
      id: '/industries/digital-twin-for-power-and-energy'
      path: '/industries/digital-twin-for-power-and-energy'
      fullPath: '/industries/digital-twin-for-power-and-energy'
      preLoaderRoute: typeof IndustriesDigitalTwinForPowerAndEnergyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/digital-twin-for-oil-and-gas': {
      id: '/industries/digital-twin-for-oil-and-gas'
      path: '/industries/digital-twin-for-oil-and-gas'
      fullPath: '/industries/digital-twin-for-oil-and-gas'
      preLoaderRoute: typeof IndustriesDigitalTwinForOilAndGasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/digital-twin-for-manufacturing': {
      id: '/industries/digital-twin-for-manufacturing'
      path: '/industries/digital-twin-for-manufacturing'
      fullPath: '/industries/digital-twin-for-manufacturing'
      preLoaderRoute: typeof IndustriesDigitalTwinForManufacturingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/digital-twin-for-cement': {
      id: '/industries/digital-twin-for-cement'
      path: '/industries/digital-twin-for-cement'
      fullPath: '/industries/digital-twin-for-cement'
      preLoaderRoute: typeof IndustriesDigitalTwinForCementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage-columns': {
      id: '/admin/manage-columns'
      path: '/admin/manage-columns'
      fullPath: '/admin/manage-columns'
      preLoaderRoute: typeof AdminManageColumnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/field-mapping': {
      id: '/admin/field-mapping'
      path: '/admin/field-mapping'
      fullPath: '/admin/field-mapping'
      preLoaderRoute: typeof AdminFieldMappingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/oil-and-gas/build-a-business-case': {
      id: '/industries/oil-and-gas/build-a-business-case'
      path: '/industries/oil-and-gas/build-a-business-case'
      fullPath: '/industries/oil-and-gas/build-a-business-case'
      preLoaderRoute: typeof IndustriesOilAndGasBuildABusinessCaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SolutionsRouteChildren {
  SolutionsDecarbonizationRoute: typeof SolutionsDecarbonizationRoute
  SolutionsMaintainAndSustainRoute: typeof SolutionsMaintainAndSustainRoute
  SolutionsPredictiveMaintenanceRoute: typeof SolutionsPredictiveMaintenanceRoute
  SolutionsProcessPerformancePredictionRoute: typeof SolutionsProcessPerformancePredictionRoute
  SolutionsRealTimeOptimizationRoute: typeof SolutionsRealTimeOptimizationRoute
  SolutionsRemotePerformanceMonitoringRoute: typeof SolutionsRemotePerformanceMonitoringRoute
  SolutionsVirtualRealityAndAugmentedRealityRoute: typeof SolutionsVirtualRealityAndAugmentedRealityRoute
  SolutionsIndexRoute: typeof SolutionsIndexRoute
}

const SolutionsRouteChildren: SolutionsRouteChildren = {
  SolutionsDecarbonizationRoute: SolutionsDecarbonizationRoute,
  SolutionsMaintainAndSustainRoute: SolutionsMaintainAndSustainRoute,
  SolutionsPredictiveMaintenanceRoute: SolutionsPredictiveMaintenanceRoute,
  SolutionsProcessPerformancePredictionRoute:
    SolutionsProcessPerformancePredictionRoute,
  SolutionsRealTimeOptimizationRoute: SolutionsRealTimeOptimizationRoute,
  SolutionsRemotePerformanceMonitoringRoute:
    SolutionsRemotePerformanceMonitoringRoute,
  SolutionsVirtualRealityAndAugmentedRealityRoute:
    SolutionsVirtualRealityAndAugmentedRealityRoute,
  SolutionsIndexRoute: SolutionsIndexRoute,
}

const SolutionsRouteWithChildren = SolutionsRoute._addFileChildren(
  SolutionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SlugRoute: SlugRoute,
  AboutUsRoute: AboutUsRoute,
  AiInPharmaceuticalManufacturingRoute: AiInPharmaceuticalManufacturingRoute,
  BuildABusinessCaseRoute: BuildABusinessCaseRoute,
  CementIndustryWhitepaperRoute: CementIndustryWhitepaperRoute,
  CompanyRoute: CompanyRoute,
  ContactRoute: ContactRoute,
  DigitalTwinFaqRoute: DigitalTwinFaqRoute,
  IntelligentDemandForecastRoute: IntelligentDemandForecastRoute,
  PowerIndustryCaseStudyRoute: PowerIndustryCaseStudyRoute,
  PowerIndustryWhitepaperRoute: PowerIndustryWhitepaperRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ReInventingTurnaroundsInTheMetaverseRoute:
    ReInventingTurnaroundsInTheMetaverseRoute,
  RenewableEnergyWhitepaperRoute: RenewableEnergyWhitepaperRoute,
  RequestADemoRoute: RequestADemoRoute,
  SignalMinerContactRoute: SignalMinerContactRoute,
  SocialDigitalRoute: SocialDigitalRoute,
  SocialDigitalContactRoute: SocialDigitalContactRoute,
  SolutionsRoute: SolutionsRouteWithChildren,
  TheindustrialmetaverseRoute: TheindustrialmetaverseRoute,
  UtilitiesControlCenterRoute: UtilitiesControlCenterRoute,
  ViziCopilotGenAiDemoLinkRoute: ViziCopilotGenAiDemoLinkRoute,
  VrTourRequestRoute: VrTourRequestRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminFieldMappingRoute: AdminFieldMappingRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminManageColumnsRoute: AdminManageColumnsRoute,
  IndustriesDigitalTwinForCementRoute: IndustriesDigitalTwinForCementRoute,
  IndustriesDigitalTwinForManufacturingRoute:
    IndustriesDigitalTwinForManufacturingRoute,
  IndustriesDigitalTwinForOilAndGasRoute:
    IndustriesDigitalTwinForOilAndGasRoute,
  IndustriesDigitalTwinForPowerAndEnergyRoute:
    IndustriesDigitalTwinForPowerAndEnergyRoute,
  IndustriesRenewablesEnergyRoute: IndustriesRenewablesEnergyRoute,
  IndustriesSugarBioEthanolIndustryRoute:
    IndustriesSugarBioEthanolIndustryRoute,
  InsightsInsightsDigitalTwinResourceCenterRoute:
    InsightsInsightsDigitalTwinResourceCenterRoute,
  PlatformMicrosoftFabricExpertiseRoute: PlatformMicrosoftFabricExpertiseRoute,
  PlatformSignalMinerRoute: PlatformSignalMinerRoute,
  PlatformVPlantRoute: PlatformVPlantRoute,
  PlatformVSmartDocxRoute: PlatformVSmartDocxRoute,
  PlatformViziCopilotRoute: PlatformViziCopilotRoute,
  PlatformViziCopilotGenAiRoute: PlatformViziCopilotGenAiRoute,
  ServicesSlugRoute: ServicesSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
  IndustriesOilAndGasBuildABusinessCaseRoute:
    IndustriesOilAndGasBuildABusinessCaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
